### PR TITLE
adding support for spring boot configuration processor. LocalProvider…

### PR DESCRIPTION
**Pull request by scalony2002**
…Configuration, LocalIdentityProviderConfiguration and LocalServiceProviderConfiguration changed to follow JavaBean pattern, adding @NestedConfigurationProperty annotation. Furthermore Builders created for those classes.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@scalony2002 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-saml&pullRequestId=306)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security-saml&pullRequestId=306) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@scalony2002 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-saml&pullRequestId=306)!

**Comment by fhanik** [comment]
@scalony2002,
hi Marek, If this depends on a compile time dependency on Spring Boot, then I won't be able to include that in core library. 

I'm wondering if we could/should create a separate auto config module, that depends on SAML core and Spring Boot, to be used for Spring boot users. And importing the auto config library would automatically get you the boot and the SAML core dependency.

**Comment by rwinch** [comment]
We typically merge Boot specific components into the sample and when ready create a ticket with Boot pointing at our sample. Once Boot provides the same functionality we remove our custom code in the sample

**Comment by scalony2002** [comment]
@fhanik Hi Filip, 
For metadata to be correctly generated spring-boot-configuration-processor need to see the annotations @NestedConfigurationProperty and the class which is bounded to properties need to be POJO. So this pull request does those two things. Technically if you have an spring-boot annotation on a class yet you are running the code in non spring-boot environment then jvm will simply ignore this annotation. However this does not seems like the right approach. I think what you propose, creating separate module to handle spring boot auto configuration is much better approach.

If you agree this is what you want to do I could help you with doing it.

**Comment by fhanik** [comment]
@scalony2002 Once again thank you so much for your contribution. I do believe this is important. I think adding a `boot-config` jar which depends on (spring-boot , spring-saml-core) is not a bad idea. 

I've started working on this at: https://github.com/spring-projects/spring-security-saml/tree/6e6f14d78a91191e7336823375d0bccaed061ad1/boot-config

It will be the brand [feature/boot-config](https://github.com/spring-projects/spring-security-saml/tree/feature/boot-config)

**Comment by fhanik** [comment]
This will be part of the next release.

Code base: https://github.com/spring-projects/spring-security-saml/tree/a29409aed34c408c679679eafe423d52ff40d42f/boot-config/src/main/java/org/springframework/security/saml/boot/registration

**Pull request closed without merging**
